/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_entropia_can_CanSocket_CanInterface */

#ifndef _Included_de_entropia_can_CanSocket_CanInterface
#define _Included_de_entropia_can_CanSocket_CanInterface
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
